spring.application.name=backend
server.port=8080
#spring.datasource.url=jdbc:sqlserver://DESKTOP-7J2PC64\\SQLMASTER;databaseName=ServerVault;encrypt=false;trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://SUPPORT-1\\MASTERSQL;databaseName=ServerVault;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.enabled=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type=ERROR
